#!/usr/bin/env python3
"""
Convert Piskel .c sprite files to CPC Mode 1 byte arrays for xroach.

Piskel stores pixels as uint32_t ABGR values:
  0xff000000 = opaque black = roach body (ink 3)
  0x00000000 = transparent  = background (ink 1)

CPC Mode 1 encodes 4 pixels per byte:
  byte = (p0_lo<<7)|(p1_lo<<6)|(p2_lo<<5)|(p3_lo<<4)
        |(p0_hi<<3)|(p1_hi<<2)|(p2_hi<<1)|(p3_hi<<0)
  ink 1 (01): p_lo=1, p_hi=0  -> background, 4px = 0xF0
  ink 3 (11): p_lo=1, p_hi=1  -> body, flip hi-bit of corresponding nibble

Usage:
  python3 roaches/convert.py          # prints C snippet to stdout
  python3 roaches/convert.py --update # patches xroach.c in place
"""

import re
import sys
import os

ROACH_DIR = os.path.join(os.path.dirname(__file__))
XROACH_C  = os.path.join(os.path.dirname(__file__), '..', 'xroach.c')

# Order must match m1_spr indexing: 0=E 1=S 2=W 3=N
SPRITES = [
    ('right_roach.c', 'E (east)'),
    ('down_roach.c',  'S (south)'),
    ('left_roach.c',  'W (west)'),
    ('up_roach.c',    'N (north)'),
]

def parse_piskel(path):
    with open(path) as f:
        content = f.read()
    # Grab the innermost {...} block containing the pixel data
    m = re.search(r'\{\s*\n([\s\S]+?)\n\}', content)
    if not m:
        raise ValueError(f"No pixel data found in {path}")
    tokens = re.findall(r'0x[0-9a-fA-F]+', m.group(1))
    if len(tokens) != 256:
        raise ValueError(f"Expected 256 pixels, got {len(tokens)} in {path}")
    return [int(t, 16) for t in tokens]

def to_mode1_bytes(pixels):
    out = []
    for row in range(16):
        for col in range(4):
            b = 0xF0  # 4 pixels of ink 1 (background)
            for k in range(4):
                if pixels[row * 16 + col * 4 + k] != 0:
                    b |= (0x08 >> k)  # set hi-bit -> ink 3 (body)
            out.append(b)
    return out

def render_array(all_bytes):
    lines = []
    lines.append('/* CPC Mode 1 sprites: 16 rows x 4 bytes = 64 bytes each */')
    lines.append('/* Order: 0=E 1=S 2=W 3=N  (generated by roaches/convert.py) */')
    lines.append('static const unsigned char m1_spr_rom[4][64] = {')
    for (_, direction), sprite_bytes in zip(SPRITES, all_bytes):
        lines.append(f'    /* {direction} */')
        lines.append('    {')
        for row in range(16):
            chunk = sprite_bytes[row*4:(row+1)*4]
            hex_vals = ', '.join(f'0x{b:02X}' for b in chunk)
            sep = ',' if row < 15 else ''
            lines.append(f'        {hex_vals}{sep}')
        lines.append('    },')
    lines.append('};')
    return '\n'.join(lines)

def main():
    all_bytes = []
    for filename, _ in SPRITES:
        path = os.path.join(ROACH_DIR, filename)
        pixels = parse_piskel(path)
        all_bytes.append(to_mode1_bytes(pixels))

    snippet = render_array(all_bytes)

    if '--update' in sys.argv:
        with open(XROACH_C) as f:
            src = f.read()
        marker_start = '/* BEGIN GENERATED SPRITES */'
        marker_end   = '/* END GENERATED SPRITES */'
        block = f'{marker_start}\n{snippet}\n{marker_end}'
        if marker_start in src:
            src = re.sub(
                re.escape(marker_start) + r'[\s\S]*?' + re.escape(marker_end),
                block,
                src
            )
        else:
            print("ERROR: markers not found in xroach.c — add them manually.", file=sys.stderr)
            sys.exit(1)
        with open(XROACH_C, 'w') as f:
            f.write(src)
        print(f"Updated {XROACH_C}")
    else:
        print(snippet)

if __name__ == '__main__':
    main()
